version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=nidal
      - MYSQL_PASSWORD=supersecret
  springboot-docker-container:
    image:  nidalino10/environnementcrud:springbootenv
    container_name: springboot-docker-container
    ports:
      - 9595:9595
    #build:
     # context: ./
      #dockerfile: Dockerfile
    depends_on:
      - mysql-standalone